CLUSTER_NAME: PETCLINIC_EKS_CLUSTER_NAME
    DOCKER_LOGIN: PETCLINIC_DOCKER_USERNAME
    DOCKER_PASSWORD: PETCLINIC_DOCKER_PASSWORD
    ACCESS_KEY_ID: ACCESS_KEY_ID
    SECRET_ACCESS_KEY: SECRET_ACCESS_KEY
    REGION: PETCLINIC_REGION
